# -*- coding: utf-8 -*-
# Best-effort transcription of the 18 uploaded faculty timetable screenshots.
# Rows marked review=1 had overlapping/unclear text in the source image and
# should be double-checked against the original screenshot before relying on them.
import csv

rows = [
# faculty, day, p_start, p_end, class_section, subject, room, group, review
("Aarti Kaushik","Mo",1,1,"CSE 5A/5B/5C/5D","Introduction to NoSQL Databases (L)","HT09","",0),
("Aarti Kaushik","Mo",6,7,"AIML 3A","Artificial Intelligence Lab","LAB06","Group 2",0),
("Aarti Kaushik","Mo",8,9,"CSE 5A/5B/5C","NoSQL Databases Lab","LAB03","G6",0),
("Aarti Kaushik","Tu",6,6,"CSE 5A/5B/5C/5D","Introduction to NoSQL Databases (L)","HT10","",1),
("Aarti Kaushik","Tu",7,7,"CSE 3A/3B/3C","Python for Data Science (L)","LS09","",1),
("Aarti Kaushik","Tu",8,9,"CSE 3A/3B/3C/M.E-3-S.M.A&E.V","Python for Data Science (L)","LF03","",0),
("Aarti Kaushik","We",3,4,"AIML 3A","Artificial Intelligence Lab","LAB07","Group 1",0),
("Aarti Kaushik","Fr",1,1,"AIML 3C/FSD 3","CST_Mentor-Mentee","LF08","",1),
("Aarti Kaushik","Fr",2,2,"AIML 3A","Artificial Intelligence","LF10","",0),
("Aarti Kaushik","Fr",8,8,"CSE 3A/3B/3C","Introduction to NoSQL Databases (L)","HT09","",1),
("Aarti Kaushik","Fr",9,10,"CSE 3A/3B/3C/M.E-3-S.M.A","Python for Data Science Lab","LAB09","Group 1",0),

("Agha Imran","Mo",1,1,"AIML 1C","Website Design-I Lab","LAB09","",0),
("Agha Imran","Mo",6,7,"CSE 1A","Website Design-I Lab","LAB09","Group 1",0),
("Agha Imran","Tu",7,7,"CSTI 5","CST_Mentor-Mentee","LF04","",0),
("Agha Imran","Tu",8,8,"CSTI 1","Introduction to Cybersecurity Lab","LAB06","",0),
("Agha Imran","We",4,4,"CSE 7C/AIML 7A/AIML 7B/AIML 7C/CDFD 7/CSTI 7","Green Computing (L)","HT08","",0),
("Agha Imran","We",6,7,"CSE 1A","Website Design-I Lab","LAB06","Group 2",0),
("Agha Imran","Th",1,1,"CSTI 1","Introduction to Cybersecurity (L)","LS08","",0),
("Agha Imran","Th",2,2,"CSE 1A","Website Designing-I","LT03","",0),
("Agha Imran","Th",7,7,"AIML 1C","Website Designing-I","LF10","",0),
("Agha Imran","Fr",6,7,"CSE 7C/AIML 7A/AIML 7B/AIML 7C/CDFD 7/CSTI 7","Green Computing Lab","HT10","G2",0),
("Agha Imran","Fr",9,9,"FSD 5","CST_Mentor-Mentee","LF08","",0),

("Anjali Mehta","Mo",1,1,"B.Tech ECE Sem 3","Introduction to Data Structures","HS09","",0),
("Anjali Mehta","Mo",3,4,"CSE 3C","Database Management System Lab","LAB03","Group 1",0),
("Anjali Mehta","Mo",8,9,"AIML 5A/AIML 5B/FSD 5/CSTI 5","NoSQL Databases Lab","LAB08","G8",0),
("Anjali Mehta","Tu",6,6,"M.E-6 S.M.A","ME-Data Structures (L)","HF08","",0),
("Anjali Mehta","Tu",7,7,"CSE 3C","Database Management System (L)","LT10","",0),
("Anjali Mehta","Tu",9,9,"AIML 3B","CST_Mentor-Mentee","LF08","",0),
("Anjali Mehta","We",1,1,"CSE 3C","Database Management System (L)","LF03","",0),
("Anjali Mehta","We",6,6,"B.Tech ECE Sem 3","Introduction to Data Structures","HS09","",0),
("Anjali Mehta","We",8,9,"B.Tech ECE Sem 3","Introduction to Data Structures Lab","LAB04","",0),
("Anjali Mehta","Th",1,1,"M.E-5 S.M.A","ME-Data Structures LEC","HF04","",0),
("Anjali Mehta","Fr",1,1,"CSE 3C","Database Management System","LAB02","Group 2",0),
("Anjali Mehta","Fr",2,2,"M.E-5 S.M.A","ME-Data Structures Lab","NG04","",0),
("Anjali Mehta","Fr",7,7,"CSE 3C","Database Management System (L)","LT09","",0),

("Annu Mishra","Mo",1,1,"AIML 5B/FSD 5/CSTI 5","Network Security & Cryptography (L)","HF09","",0),
("Annu Mishra","Mo",2,2,"CSE 7A","CST_Mentor-Mentee","KS08","",0),
("Annu Mishra","Mo",6,6,"AIML 1B","PS Using C Lab","LAB04","Group 1",1),
("Annu Mishra","Mo",7,7,"AIML 5B/FSD 5/CSTI 5","Network Security & Cryptography Lab","LF08","G2",1),
("Annu Mishra","Tu",3,3,"FSD 5/CSTI 5","Advanced Java (L)","LT09","",0),
("Annu Mishra","Tu",6,7,"AIML 5B/FSD 5/CSTI 5","Network Security & Cryptography (L)","HS02","",0),
("Annu Mishra","We",1,1,"AIML 1B","PS Using C Lab","LAB08","Group 1",0),
("Annu Mishra","We",4,4,"FSD 5/CSTI 5","Advanced Java (L)","LF10","",0),
("Annu Mishra","Th",1,1,"FSD 5/CSTI 5","Advanced Java (L)","LF03","",0),
("Annu Mishra","Fr",1,1,"FSD 5/CSTI 5","Advanced Java Lab","LAB IF02","",0),
("Annu Mishra","Fr",8,8,"AIML 5B/FSD 5/CSTI 5","Network Security & Cryptography (L)","HF09","",0),

("Anup Singh Kushwaha","Mo",2,2,"BBA BA Sem V","SOB_Website Designing","IS06","",0),
("Anup Singh Kushwaha","Mo",6,6,"BCA CC 1","Fundamentals of Cloud Computing (L)","KS08","",0),
("Anup Singh Kushwaha","Tu",1,1,"CSTI 3","Network Defense & Application Security (L)","LS04","",0),
("Anup Singh Kushwaha","Tu",2,3,"BBA EFB Sem V/BBA FAA Sem V","SOB_Website Designing","LAB IG10","",0),
("Anup Singh Kushwaha","Tu",6,6,"BBA BA Sem V","SOB_Website Designing","LAB IG10","",0),
("Anup Singh Kushwaha","Tu",9,9,"AIML 5A","CST_Mentor-Mentee","LS04","",0),
("Anup Singh Kushwaha","We",7,7,"CSTI 3","Network Defense & Application Security (L)","LS04","",0),
("Anup Singh Kushwaha","Th",2,2,"BCA CC 1","Fundamentals of Cloud Computing (L)","LT04","",0),
("Anup Singh Kushwaha","Th",6,6,"BBA FAA Sem V/BBA EFB Sem V","SOB_Website Designing","IS07","",0),
("Anup Singh Kushwaha","Fr",1,1,"CSTI 3","Network Defense & Application Security Lab","LAB03","",0),
("Anup Singh Kushwaha","Fr",6,6,"BCA CC 1","Fundamentals of Cloud Computing (L)","LT08","",0),
("Anup Singh Kushwaha","Fr",8,9,"BCA CC 1","Fundamentals of Cloud Computing Lab","","",0),

("Anupriya Sharma","Mo",2,2,"B.Tech ECE Sem 7","Cloud Computing","HS08","",0),
("Anupriya Sharma","Mo",3,3,"CSE 3B","Database Management System (L)","KS09","",0),
("Anupriya Sharma","Mo",6,7,"CSE 3B","Database Management System Lab","LAB IF02","Group 1",0),
("Anupriya Sharma","Tu",1,1,"CSE 3B","Database Management System Lab","LAB02","Group 2",0),
("Anupriya Sharma","Tu",3,3,"AIML 3A","Database Management System (L)","KS10","",0),
("Anupriya Sharma","Tu",6,6,"CSE 3B","Database Management System (L)","KS09","",0),
("Anupriya Sharma","Tu",7,7,"B.Tech ECE Sem 7","Cloud Computing","HS02","",0),
("Anupriya Sharma","We",1,1,"CSE 3B","Database Management System (L)","LS03","",0),
("Anupriya Sharma","We",6,6,"B.Tech ECE Sem 7","Cloud Computing","HS02","",0),
("Anupriya Sharma","We",8,8,"AIML 3A","Database Management System (L)","LF10","",0),
("Anupriya Sharma","Th",6,7,"AIML 3A","Database Management System Lab","LAB03","Group 1",0),
("Anupriya Sharma","Fr",1,1,"CSE 5B","CST_Mentor-Mentee","HF09","",0),
("Anupriya Sharma","Fr",3,3,"AIML 3A","Database Management System Lab","LAB09","Group 2",0),
("Anupriya Sharma","Fr",9,9,"AIML 3A","Database Management System (L)","LT10","",0),

("Babita Yadav","Mo",4,4,"CSE 3A","OOPs Using Java","KS02","",0),
("Babita Yadav","Mo",6,7,"CSE 3A","OOPs Using Java Lab","LAB02","Group 2",0),
("Babita Yadav","Tu",3,3,"CSE 3A","OOPs Using Java","LT03","",0),
("Babita Yadav","Tu",7,7,"CSE 5A","Advanced Java (L)","HT09","",0),
("Babita Yadav","We",3,3,"CSE 5A","Advanced Java Lab","LAB IG10","Group 2",0),
("Babita Yadav","We",6,6,"CSE 5A","Advanced Java (L)","KS09","",0),
("Babita Yadav","We",7,7,"CSE 3A","OOPs Using Java Lab","LAB03","Group 1",0),
("Babita Yadav","Th",1,1,"CSE 5A","Advanced Java Lab","LAB09","Group 1",0),
("Babita Yadav","Th",6,6,"CSE 3A","OOPs Using Java","KS02","",0),
("Babita Yadav","Th",7,7,"CSE 5A","Advanced Java (L)","LT03","",0),
("Babita Yadav","Fr",8,8,"CSE 3A","CST_Mentor-Mentee","LF04","",0),

("Bhawna","Mo",1,1,"BCA CC3/BCA FinTech3","Modern Database Management Lab","LAB06","",0),
("Bhawna","Mo",2,2,"AIML 7B","CST_Mentor-Mentee","LS04","",0),
("Bhawna","Mo",8,8,"AIML 3B","Database Management System Lab","LF10","Group 2",0),
("Bhawna","Tu",2,2,"BCA FinTech3","AI for Financial Modelling","KS08","",0),
("Bhawna","Tu",8,8,"AIML 3B","Database Management System (L)","LS10","",0),
("Bhawna","We",1,1,"AIML 3B","Database Management System Lab","NG04","Group 1",0),
("Bhawna","We",3,3,"BCA CC3/BCA FinTech3","Modern Database Management (L)","KS08","",0),
("Bhawna","We",6,6,"AIML 3B","Database Management System (L)","LS10","",0),
("Bhawna","We",7,7,"BCA CC3/BCA FinTech3","Modern Database Management (L)","LF08","",0),
("Bhawna","Fr",6,6,"BCA CC3/BCA FinTech3","Modern Database Management (L)","LS08","",0),
("Bhawna","Fr",7,7,"AIML 3B","Database Management System (L)","LT03","",0),
("Bhawna","Fr",8,8,"CSE 7C/AIML 7A/AIML 7B/AIML 7C/CDFD 7/CSTI 7","User Experience Lab","LS10","Group 3",0),

("Chandni Magoo","Mo",4,4,"AIML 7A","Computer Vision & Data Visualization (L)","LAB05","",0),
("Chandni Magoo","Mo",6,6,"CSE 1B","PS Using C (L)","LT09","",0),
("Chandni Magoo","We",6,6,"AIML 7A","Computer Vision & Data Visualization (L)","KS03","",0),
("Chandni Magoo","We",7,7,"AIML 7A","Computer Vision & Data Visualization (L)","KS03","",0),
("Chandni Magoo","Th",4,4,"M.Tech CSE 3","Dissertation","LF04","",1),
("Chandni Magoo","Th",4,4,"CSE 1B","PS Using C (L)","LT04","",1),
("Chandni Magoo","Th",7,7,"CSE 1B","PS Using C Lab","LAB07","",0),
("Chandni Magoo","Fr",6,7,"CSE 1B","PS Using C Lab","LAB07","",0),

("Deepanshi Gupta","Mo",1,1,"AIML 1B","Website Design-I Lab","LAB07","Group 2",0),
("Deepanshi Gupta","Mo",7,7,"CSE 1B","Website Designing-I","LT03","",0),
("Deepanshi Gupta","Tu",2,2,"AIML 1B","Website Designing-I","KS10","",0),
("Deepanshi Gupta","Tu",8,8,"CSE 1B","Website Design-I Lab","LAB01","",0),
("Deepanshi Gupta","We",3,3,"AIML 1A","Website Design-I Lab","LAB09","Group 1",0),
("Deepanshi Gupta","We",6,6,"BCA CC3/BCA FinTech3","Networks and Communication","LS04","",0),
("Deepanshi Gupta","We",7,7,"CDFD 7","CST_Mentor-Mentee","LT08","",0),
("Deepanshi Gupta","We",8,8,"AIML 1A","Website Design-I Lab","LAB01","Group 2",0),
("Deepanshi Gupta","Th",1,1,"BCA CC3/BCA FinTech3","Networks and Communication","LS04","",0),
("Deepanshi Gupta","Th",2,2,"AIML 1A","Website Designing-I","LF09","",0),
("Deepanshi Gupta","Fr",1,1,"AIML 1B","Website Design-I Lab","LAB09","Group 1",0),
("Deepanshi Gupta","Fr",4,4,"BCA CC3/BCA FinTech3","Networks and Communication","LT04","",0),
("Deepanshi Gupta","Fr",8,8,"CDFD 7/CSTI 7","Image Editing & Animation Workshop","LAB07","Group 8",0),

("Deepti Thakral","Mo",8,8,"BCA CC 1","CST_Mentor-Mentee","LS04","",0),
("Deepti Thakral","We",3,3,"FSD 5/CSTI 5","Operating Systems (L)","LF03","",0),
("Deepti Thakral","We",4,4,"CSE 5B","Computer Architecture & Organisation (L)","LT03","",0),
("Deepti Thakral","We",6,6,"CSE 5B","Computer Architecture & Organisation (L)","HT04","",0),
("Deepti Thakral","We",7,7,"FSD 5/CSTI 5","Operating Systems (L)","LS10","",0),
("Deepti Thakral","We",8,8,"CSE 7A/CSE 7B/CSE 7C","Data Visualization with Tableau Lab","LAB02","Group 9",0),
("Deepti Thakral","Th",1,1,"CSTI 3","CST_Mentor-Mentee","LF04","",0),
("Deepti Thakral","Th",2,2,"FSD 5/CSTI 5","Operating Systems (L)","KS02","",0),
("Deepti Thakral","Th",3,4,"FSD 5/CSTI 5","Operating Systems Lab","LAB02","",0),
("Deepti Thakral","Th",6,7,"CSE 5B","Computer Architecture & Organisation Lab","NG04","Group 2",0),
("Deepti Thakral","Fr",2,2,"CSE 5B","Computer Architecture & Organisation (L)","LT09","",0),
("Deepti Thakral","Fr",3,4,"CSE 5B","Computer Architecture & Organisation Lab","LAB01","Group 1",0),

("Dimple Saproo","Mo",6,6,"CSTI 3/B.Tech GenAI 3","Artificial Intelligence","LF03","",0),
("Dimple Saproo","Tu",1,1,"CSE 3C","Machine Learning","LF03","",0),
("Dimple Saproo","Tu",3,3,"CSTI 3/B.Tech GenAI 3","Artificial Intelligence","KS09","",0),
("Dimple Saproo","Tu",8,8,"B.Tech GenAI 3","Artificial Intelligence Lab","LAB08","",0),
("Dimple Saproo","We",2,2,"CSE 3C","Machine Learning Lab","LAB02","Group 2",0),
("Dimple Saproo","We",6,6,"CSE 3C","Machine Learning","LT03","",0),
("Dimple Saproo","We",8,8,"AIML 7B/AIML 7C/CDFD 7/CSTI 7/AIML 7A","Agile Technologies Workshop","LAB IG10","Group 5",0),
("Dimple Saproo","Th",4,4,"CSE 3C","Machine Learning","LT09","",0),
("Dimple Saproo","Fr",1,1,"CSE 3C","Machine Learning Lab","LAB07","Group 1",0),
("Dimple Saproo","Fr",8,8,"CSTI 3","Artificial Intelligence Lab","LAB06","",0),

("Esha","Tu",4,4,"CSE 3B","OOPs Using Java","LT10","",0),
("Esha","Tu",7,7,"CSE 5B","Advanced Java (L)","LF03","",0),
("Esha","We",1,1,"CSE 5B","Advanced Java Lab","LAB IG10","Group 1",0),
("Esha","We",2,2,"CSE 3B","OOPs Using Java Lab","LAB01","Group 1",0),
("Esha","We",6,6,"CSE 3B","OOPs Using Java","LT09","",0),
("Esha","We",9,9,"CSE 3B","CST_Mentor-Mentee","LF04","",0),
("Esha","Th",2,2,"CSE 3B","OOPs Using Java","LT03","",0),
("Esha","Th",4,4,"CSE 5B","Advanced Java (L)","HT10","",0),
("Esha","Th",7,7,"CSE 3B","OOPs Using Java Lab","LAB01","Group 2",0),
("Esha","Fr",2,2,"CSE 5B","Advanced Java Lab","LAB03","Group 2",0),
("Esha","Fr",6,6,"CSE 5B","Advanced Java (L)","HS02","",0),

("Ganga Sharma","Mo",2,2,"AIML 3B","OOPs Using Java","LS09","",0),
("Ganga Sharma","Mo",3,3,"AIML 3B","OOPs Using Java Lab","LAB08","Group 1",0),
("Ganga Sharma","Mo",7,7,"BCA CC3/BCA FinTech3","Foundations of OOPs Using Java (L)","KS09","",0),
("Ganga Sharma","Mo",8,8,"B.Tech GenAI 3/CSTI 3","Introduction to Research","LT04","",0),
("Ganga Sharma","Tu",3,3,"BCA CC3/BCA FinTech3","Foundations of OOPs Using Java Lab","LAB06","",0),
("Ganga Sharma","Tu",8,8,"AIML 3B","OOPs Using Java","LS03","",0),
("Ganga Sharma","Th",2,2,"B.Tech GenAI 3","CST_Mentor-Mentee","LF08","",0),
("Ganga Sharma","Th",3,3,"BCA CC3/BCA FinTech3","Foundations of OOPs Using Java Lab","LAB08","",0),
("Ganga Sharma","Th",6,6,"BCA CC3/BCA FinTech3","Foundations of OOPs Using Java (L)","LT08","",0),
("Ganga Sharma","Fr",2,2,"AIML 3B","OOPs Using Java","LS09","",0),
("Ganga Sharma","Fr",3,3,"AIML 3B","OOPs Using Java Lab","LAB04","Group 2",0),

("Gunjan Aggarwal","Mo",1,1,"AIML 5A/AIML 5B/FSD 5/CSTI 5","Introduction to NoSQL Databases (L)","KS02","",0),
("Gunjan Aggarwal","Mo",6,6,"FSD 5/CSTI 5","Computer Architecture & Organisation (L)","KS10","",0),
("Gunjan Aggarwal","Mo",7,7,"B.Tech ECE Sem 1","Programming for problem solving using C","HS07","",0),
("Gunjan Aggarwal","Mo",8,9,"CSE 5C/CSE 5D/AIML 5A","NoSQL Databases Lab","LAB07","G7",0),
("Gunjan Aggarwal","Tu",1,1,"FSD 5/CSTI 5","Computer Architecture & Organisation Lab","KS03","",0),
("Gunjan Aggarwal","Tu",4,4,"FSD 5/CSTI 5","Computer Architecture & Organisation (L)","LF03","",0),
("Gunjan Aggarwal","Tu",6,6,"AIML 5A/AIML 5B/FSD 5/CSTI 5","Introduction to NoSQL Databases (L)","HF03","",0),
("Gunjan Aggarwal","Tu",8,8,"B.Tech ECE Sem 1","Programming for problem solving using C Lab","LAB04","",0),
("Gunjan Aggarwal","We",1,1,"FSD 5/CSTI 5","Computer Architecture & Organisation (L)","LT03","",0),
("Gunjan Aggarwal","We",8,8,"CSE 3C","CST_Mentor-Mentee","LF08","",0),
("Gunjan Aggarwal","Th",6,6,"B.Tech ECE Sem 1","Programming for problem solving using C Lab","NS-05","",0),
("Gunjan Aggarwal","Fr",2,2,"B.Tech ECE Sem 1","Programming for problem solving using C","HT10","",0),
("Gunjan Aggarwal","Fr",8,8,"AIML 5A/AIML 5B/FSD 5/CSTI 5","Introduction to NoSQL Databases (L)","HT10","",0),

("Gunjan Chandwani","Mo",4,4,"AIML 3A","OOPs Using Java","LF09","",0),
("Gunjan Chandwani","Mo",6,6,"AIML 5B","Advanced Java (L)","LT10","",0),
("Gunjan Chandwani","Tu",3,3,"AIML 5B","Advanced Java (L)","LT10","",0),
("Gunjan Chandwani","Tu",8,8,"AIML 5B","CST_Mentor-Mentee","LF04","",0),
("Gunjan Chandwani","We",3,3,"AIML 3A","OOPs Using Java Lab","LAB08","Group 2",0),
("Gunjan Chandwani","We",6,6,"AIML 5B","Advanced Java Lab","LAB07","Group 1",0),
("Gunjan Chandwani","Th",1,1,"AIML 5B","Advanced Java Lab","LAB03","Group 2",0),
("Gunjan Chandwani","Th",3,3,"AIML 3A","OOPs Using Java","LT10","",0),
("Gunjan Chandwani","Th",6,6,"AIML 5B","Advanced Java (L)","LF09","",0),
("Gunjan Chandwani","Fr",3,3,"AIML 3A","OOPs Using Java Lab","LAB08","Group 1",0),
("Gunjan Chandwani","Fr",6,6,"AIML 3A","OOPs Using Java","LT10","",0),
("Gunjan Chandwani","Fr",8,8,"CSE 7A/CSE 7B/CSE 7C/AIML 7A/AIML 7B/CDFD 7/CSTI 7","Advanced Java (Workshop)","LAB08","Group 1",0),

("Juhi","Mo",1,1,"CSE 5A/CSE 5B","Deep Learning Essentials (L)","HS02","",0),
("Juhi","Mo",8,9,"CSE 5A","Deep Learning Essentials Lab","NG04","G3",0),
("Juhi","Tu",3,3,"CSE 3A","Artificial Intelligence","LT09","",0),
("Juhi","Tu",6,6,"CSE 5A/CSE 5B","Deep Learning Essentials (L)","HS08","",0),
("Juhi","We",1,1,"CSE 3A","Artificial Intelligence Lab","LAB06","Group 2",0),
("Juhi","Th",3,3,"CSE 3A","Artificial Intelligence","KS10","",0),
("Juhi","Fr",1,1,"CSE 3A","Artificial Intelligence Lab","LAB06","Group 1",0),
("Juhi","Fr",8,8,"CSE 5A/CSE 5B","Deep Learning Essentials (L)","HS02","",0),

("Jyoti Nanwal","Mo",1,1,"B.TECH GenAI 3","Database Management System Lab","LAB02","",0),
("Jyoti Nanwal","Mo",6,6,"CSE 5A","CST_Mentor-Mentee","HF09","",0),
("Jyoti Nanwal","Mo",7,7,"B.TECH GenAI 3/CSTI 3","Database Management System (L)","LT09","",0),
("Jyoti Nanwal","Tu",3,3,"B.TECH GenAI 3/CSTI 3","Database Management System (L)","KS09","",0),
("Jyoti Nanwal","Tu",7,7,"AIML 5B","Operating Systems (L)","LT09","",0),
("Jyoti Nanwal","Tu",8,8,"CSTI 3","Database Management System Lab","LAB09","",0),
("Jyoti Nanwal","We",1,1,"AIML 5B","Operating Systems Lab","LS09","Group 1",0),
("Jyoti Nanwal","We",4,4,"B.TECH GenAI 3/CSTI 3","Database Management System (L)","KS02","",0),
("Jyoti Nanwal","We",6,6,"AIML 5B","Operating Systems Lab","LAB04","Group 2",0),
("Jyoti Nanwal","Th",7,7,"AIML 5B","Operating Systems (L)","LT09","",0),
("Jyoti Nanwal","Fr",2,2,"AIML 5B","Operating Systems (L)","LF09","",0),
("Jyoti Nanwal","Fr",8,8,"AIML 7B/CSTI 7","Data Visualization with Tableau Lab","LT04","Group 11",0),
]

with open('/home/claude/faculty-adjustment-finder/data/timetable_data.csv','w',newline='',encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(["faculty_name","day","period_start","period_end","class_section","subject","room","group","review"])
    w.writerows(rows)

print(len(rows), "rows written")
