# -*- coding: utf-8 -*-
# Second batch: 18 more faculty timetable screenshots, appended to timetable_data.csv.
import csv

rows = [
("Mahesh Swami","Mo",1,1,"CSE 3C","Artificial Intelligence Lab","LAB03","Group 2",0),
("Mahesh Swami","Mo",4,4,"AIML 3C/FSD 3","Artificial Intelligence","LF10","",0),
("Mahesh Swami","Mo",6,6,"CSE 3C","Artificial Intelligence","KS09","",0),
("Mahesh Swami","Tu",3,3,"CSE 3C","Artificial Intelligence Lab","LAB01","Group 1",0),
("Mahesh Swami","Tu",6,6,"CSE 3C","Artificial Intelligence","LT10","",0),
("Mahesh Swami","Tu",7,7,"AIML 3C","Artificial Intelligence Lab","LF09","Group 1",0),
("Mahesh Swami","We",1,1,"CSE 7B","CST_Mentor-Mentee","HF10","",0),
("Mahesh Swami","We",2,2,"AIML 3C/FSD 3","Artificial Intelligence","KS02","",0),
("Mahesh Swami","Th",1,1,"B.Tech ECE Sem 5","Mobile App Development","LAB08","",0),
("Mahesh Swami","Th",6,7,"AIML 3C/FSD 3","Artificial Intelligence Lab","LS08","Group 2",0),
("Mahesh Swami","Fr",7,7,"B.Tech ECE Sem 5","Mobile App Development","NS-05","",0),

("Mamta Arora","Mo",1,1,"AIML 3C","OOPs Using Java Lab","LAB04","Group 1",0),
("Mamta Arora","Mo",3,3,"AIML 5A","Computer Vision & Image Processing (L)","LF10","",0),
("Mamta Arora","Mo",8,8,"B.TECH GenAI 3/CSTI 3","Introduction to Research","LT04","",0),
("Mamta Arora","Tu",1,1,"AIML 3C/FSD 3","OOPs Using Java","LS09","",0),
("Mamta Arora","Tu",3,4,"AIML 3C/FSD 3","OOPs Using Java Lab","LAB09","Group 2",0),
("Mamta Arora","Tu",8,8,"AIML 5A","Computer Vision & Image Processing (L)","LF10","",0),
("Mamta Arora","Th",2,2,"AIML 5A","Computer Vision & Image Processing (L)","LF10","",0),
("Mamta Arora","Th",3,3,"B.TECH GenAI 3","Advanced Python for AI (L)","LS08","",0),
("Mamta Arora","Th",4,4,"AIML 3C/FSD 3","OOPs Using Java","LF10","",0),
("Mamta Arora","Fr",1,1,"AIML 3C/FSD 3","CST_Mentor-Mentee","LF08","",0),
("Mamta Arora","Fr",4,4,"AIML 3C/FSD 3","OOPs Using Java","KS09","",0),
("Mamta Arora","Fr",7,7,"B.TECH GenAI 3","Advanced Python for AI Lab","LAB04","",0),
("Mamta Arora","Fr",8,8,"CSE 7A/CSE 7B/CSE 7C/AIML 7A/AIML 7B/CDFD 7/CSTI 7","Big Data Lab","LT03","",0),

("Manoj Kumar","Mo",2,2,"AIML 3A","Machine Learning","LF10","",0),
("Manoj Kumar","Mo",3,3,"M.E-7 S.M.A","ME-Artificial Intelligence & Machine Learning Lec","HF08","",0),
("Manoj Kumar","Mo",8,8,"AIML 3A","Introduction to Research","LF09","",0),
("Manoj Kumar","Tu",1,1,"AIML 3A","Machine Learning","LF10","",0),
("Manoj Kumar","Tu",2,2,"AIML 5B","Computer Vision & Image Processing (L)","LF09","",0),
("Manoj Kumar","Tu",3,3,"M.E-7 S.M.A","ME-Artificial Intelligence & Machine Learning Lec","HF08","",0),
("Manoj Kumar","Tu",7,7,"M.E-7 S.M.A","ME-Artificial Intelligence & Machine Learning Lab","LAB08","",0),
("Manoj Kumar","We",1,2,"AIML 3A","Machine Learning Lab","LAB02","Group 1",0),
("Manoj Kumar","We",4,4,"AIML 5B","Computer Vision & Image Processing (L)","LS09","",0),
("Manoj Kumar","Th",1,2,"AIML 3A","Machine Learning Lab","LAB02","Group 2",0),
("Manoj Kumar","Th",3,3,"AIML 5B","Computer Vision & Image Processing (L)","LT09","",0),
("Manoj Kumar","Th",4,4,"CSE 7C","CST_Mentor-Mentee","HS08","",0),
("Manoj Kumar","Fr",1,1,"AIML 3A","Machine Learning","LF10","",0),

("Manpreet Kaur","Mo",3,3,"B.TECH GenAI 3/CSTI 3","Machine Learning","LT09","",0),
("Manpreet Kaur","Tu",1,2,"B.TECH GenAI 3","Machine Learning Lab","LAB06","",0),
("Manpreet Kaur","We",3,3,"B.TECH GenAI 3/CSTI 3","Machine Learning","LT10","",0),
("Manpreet Kaur","Th",2,3,"CSTI 3","Machine Learning Lab","LAB01","",0),
("Manpreet Kaur","Fr",2,2,"B.TECH GenAI 3/CSTI 3","Machine Learning","LT03","",0),
("Manpreet Kaur","Fr",8,8,"CSE 3B","Introduction to Research","LT08","",0),

("Meena Chaudhary","Mo",1,1,"CSTI 3","OOPs Using Java Lab","LAB01","",0),
("Meena Chaudhary","Mo",7,7,"CSE 5C","Advanced Java (L)","KS02","",0),
("Meena Chaudhary","Tu",1,1,"CSE 5C","Advanced Java Lab","LAB07","Group 1",0),
("Meena Chaudhary","Tu",7,7,"CSTI 3/B.TECH GenAI 3","OOPs Using Java","KS09","",0),
("Meena Chaudhary","We",1,1,"CSE 5C","CST_Mentor-Mentee","LF08","",0),
("Meena Chaudhary","We",4,4,"CSE 5C","Advanced Java (L)","KS09","",0),
("Meena Chaudhary","We",6,6,"CSE 5C","Advanced Java Lab","LAB02","Group 2",0),
("Meena Chaudhary","Th",6,6,"CSE 5C","Advanced Java (L)","KS09","",0),
("Meena Chaudhary","Th",7,7,"CSTI 3/B.TECH GenAI 3","OOPs Using Java","LT10","",0),
("Meena Chaudhary","Fr",1,1,"B.TECH GenAI 3","OOPs Using Java Lab","LAB04","",0),
("Meena Chaudhary","Fr",4,4,"CSTI 3/B.TECH GenAI 3","OOPs Using Java","KS02","",0),
("Meena Chaudhary","Fr",8,8,"CSE 7A/CSE 7B","User Experience Lab","LAB03","Group 2",0),

("Narender Gautam","Mo",3,3,"CSE 1A","PS Using C (L)","KS10","",0),
("Narender Gautam","Mo",8,8,"CSE 1A","PS Using C Lab","LAB04","Group 2",0),
("Narender Gautam","Tu",2,2,"AIML 3B","Artificial Intelligence","LS10","",0),
("Narender Gautam","Tu",7,7,"CSE 1A","PS Using C (L)","LT03","",0),
("Narender Gautam","We",1,1,"AIML 3B","Artificial Intelligence Lab","LS10","Group 2",0),
("Narender Gautam","We",6,6,"CSE 1A","PS Using C Lab","LAB09","Group 1",0),
("Narender Gautam","We",9,9,"AIML 3A","CST_Mentor-Mentee","LS04","",0),
("Narender Gautam","Th",1,1,"AIML 3B","Artificial Intelligence Lab","LAB07","Group 1",0),
("Narender Gautam","Th",7,7,"AIML 3B","Artificial Intelligence","LS10","",0),
("Narender Gautam","Fr",3,3,"CSE 1A","PS Using C Lab","LAB07","Group 2",0),
("Narender Gautam","Fr",7,7,"CSE 1A","PS Using C Lab","LAB IG10","Group 1",0),

("Neelu Chaudhary","Mo",2,2,"CSE 3B","Artificial Intelligence","LS03","",0),
("Neelu Chaudhary","Mo",3,3,"AIML 7A","CST_Mentor-Mentee","LF04","",0),
("Neelu Chaudhary","Mo",6,6,"CSE 3B","Artificial Intelligence Lab","LAB03","Group 2",0),
("Neelu Chaudhary","Tu",1,1,"CSE 3B","Artificial Intelligence Lab","LAB01","Group 1",0),
("Neelu Chaudhary","We",3,3,"CSE 5C","Computer Architecture & Organisation (L)","KS10","",0),
("Neelu Chaudhary","We",6,6,"CSE 5C","Computer Architecture & Organisation Lab","LAB03","Group 1",0),
("Neelu Chaudhary","Th",3,3,"CSE 5C","Computer Architecture & Organisation (L)","HS02","",0),
("Neelu Chaudhary","Fr",2,2,"CSE 3B","Artificial Intelligence","LF03","",0),
("Neelu Chaudhary","Fr",3,3,"CSE 5C","Computer Architecture & Organisation (L)","KS10","",0),
("Neelu Chaudhary","Fr",6,6,"CSE 5C","Computer Architecture & Organisation Lab","LAB02","Group 2",0),

("Parneeta Dhaliwal","Mo",1,1,"AIML 7B","Computer Vision & Data Visualization (L)","LF09","",0),
("Parneeta Dhaliwal","Mo",2,2,"AIML 7B","Computer Vision & Data Visualization (L)","LAB05","",1),
("Parneeta Dhaliwal","Mo",3,3,"AIML 3B","Machine Learning Lab","LAB02","Group 2",0),
("Parneeta Dhaliwal","Tu",3,3,"AIML 3B","Machine Learning","LF09","",0),
("Parneeta Dhaliwal","Th",1,1,"AIML 7B","Computer Vision & Data Visualization (L)","LS10","",0),
("Parneeta Dhaliwal","Th",3,3,"AIML 3B","Machine Learning","LS09","",0),
("Parneeta Dhaliwal","Fr",3,3,"AIML 3B","Machine Learning Lab","LAB02","Group 1",0),
("Parneeta Dhaliwal","Fr",6,6,"AIML 3B","Machine Learning","KS02","",0),

("Pooja Ahuja","Mo",1,1,"CSE 5A/5B/5C/5D/AIML 5A","Network Security & Cryptography (L)","HF10","",0),
("Pooja Ahuja","Mo",3,3,"BCA CC 1/BCA FinTech 1","Fundamentals of Computers and Operating Systems Lab","LAB07","",0),
("Pooja Ahuja","Mo",7,7,"AIML 3B","Introduction to Research","LS04","",0),
("Pooja Ahuja","Mo",8,9,"CSE 5A/5B/5C/5D/AIML 5A","Network Security & Cryptography Lab","LAB06","G1",0),
("Pooja Ahuja","Tu",6,6,"CSE 5A/5B/5C/5D/AIML 5A","Network Security & Cryptography (L)","HF10","",0),
("Pooja Ahuja","We",8,8,"CSE 7A/CSE 7B/CSE 7C","Agile Technologies Workshop","LAB09","Group 4",0),
("Pooja Ahuja","Th",2,2,"BCA FinTech 1","CST_Mentor-Mentee","LT08","",0),
("Pooja Ahuja","Th",3,3,"BCA CC 1/BCA FinTech 1","Fundamentals of Computers and Operating Systems (L)","LT04","",0),
("Pooja Ahuja","Th",6,6,"BCA CC 1/BCA FinTech 1","Fundamentals of Computers and Operating Systems (L)","LF04","",0),
("Pooja Ahuja","Fr",6,6,"BCA CC 1/BCA FinTech 1","Fundamentals of Computers and Operating Systems (L)","LF04","",0),
("Pooja Ahuja","Fr",8,8,"CSE 5A/5B/5C/5D/AIML 5A","Network Security & Cryptography (L)","HF10","",0),

("Prinima Gupta","Mo",4,4,"CSE 5A","Computer Architecture & Organisation (L)","HS02","",0),
("Prinima Gupta","Mo",8,8,"CSE 3A","Introduction to Research","LS08","",0),
("Prinima Gupta","Tu",3,3,"CSE 5A","Computer Architecture & Organisation Lab","LAB04","Group 1",0),
("Prinima Gupta","We",6,6,"CSE 5A","Computer Architecture & Organisation (L)","HF09","",0),
("Prinima Gupta","Th",1,1,"CSE 5A","Computer Architecture & Organisation Lab","LAB04","Group 2",0),
("Prinima Gupta","Fr",3,3,"CSE 5A","Computer Architecture & Organisation (L)","HF09","",0),
("Prinima Gupta","Fr",8,8,"CSE 7A/CSE 7B","Image Editing & Animation Workshop","LAB02","Group 6",0),

("Pushpa","Mo",3,3,"CSTI 1/B.Tech GenAI 1/B.TECH QUANTUM 1","Website Designing-I","LF08","",0),
("Pushpa","Mo",6,6,"CSE 5B","Operating Systems (L)","KS02","",0),
("Pushpa","Mo",7,7,"AIML 1C","PS Using C (L)","LF08","",0),
("Pushpa","Tu",2,2,"CSE 5B","Operating Systems (L)","LT03","",0),
("Pushpa","Tu",6,7,"AIML 1C","PS Using C Lab","LAB07","",0),
("Pushpa","We",1,1,"CSE 5B","Operating Systems Lab","LAB09","Group 2",0),
("Pushpa","We",2,2,"AIML 1C","PS Using C (L)","LS04","",0),
("Pushpa","We",6,7,"AIML 1C","PS Using C Lab","LAB08","",0),
("Pushpa","Th",2,2,"CSE 5B","Operating Systems (L)","KS09","",0),
("Pushpa","Th",6,6,"CSE 5B","Operating Systems Lab","LAB IF02","Group 1",0),
("Pushpa","Fr",1,1,"CSE 5B","CST_Mentor-Mentee","HF09","",0),
("Pushpa","Fr",6,6,"CSTI 1/B.Tech GenAI 1/B.TECH QUANTUM 1","Website Design-I Lab","LAB08","",0),

("Ram Chatterjee","Mo",3,3,"CSE 3C","OOPs Using Java Lab","LAB04","Group 2",0),
("Ram Chatterjee","Mo",6,6,"BCA FinTech 1","Foundation of Finance Technology","LT04","",0),
("Ram Chatterjee","Mo",7,7,"CSE 3C","OOPs Using Java","LF03","",0),
("Ram Chatterjee","Tu",1,1,"AIML 5A","Advanced Java Lab","LAB05","Group 1",0),
("Ram Chatterjee","Tu",7,7,"AIML 5A","Advanced Java (L)","LF10","",0),
("Ram Chatterjee","We",3,3,"CSE 3C","OOPs Using Java Lab","LAB03","Group 1",0),
("Ram Chatterjee","We",8,8,"BCA FinTech 1","Foundation of Finance Technology","LF08","",0),
("Ram Chatterjee","We",9,9,"CSE 3C","CST_Mentor-Mentee","LF08","",0),
("Ram Chatterjee","Th",1,1,"CSE 3C","OOPs Using Java","LT10","",0),
("Ram Chatterjee","Th",6,6,"AIML 5A","Advanced Java (L)","LS10","",0),
("Ram Chatterjee","Th",7,7,"BCA FinTech 1","Foundation of Finance Technology","LF04","",0),
("Ram Chatterjee","Fr",1,1,"AIML 5A","Advanced Java (L)","LS09","",0),
("Ram Chatterjee","Fr",3,3,"CSE 3C","OOPs Using Java","LT10","",0),
("Ram Chatterjee","Fr",6,6,"AIML 5A","Advanced Java Lab","LS10","Group 2",0),
("Ram Chatterjee","Fr",8,8,"AIML 7A/AIML 7C","Data Visualization with Tableau Lab","LS08","Group 10",0),

("Ranjna Jain","Mo",1,1,"B.Tech GenAI 1","Data Modelling & Visualization Lab","LAB08","",0),
("Ranjna Jain","Mo",3,3,"CSE 5D","Advanced Java Lab","LAB06","Group 2",0),
("Ranjna Jain","Mo",7,7,"M.TECH CSE 3","Paedagogical Skills (L)","LF04","",0),
("Ranjna Jain","Tu",1,1,"CSE 5D","Advanced Java Lab","LAB IF02","Group 1",0),
("Ranjna Jain","Tu",8,8,"B.Tech GenAI 1","Data Modelling & Visualization (L)","LF08","",0),
("Ranjna Jain","Tu",9,9,"AIML 3B","CST_Mentor-Mentee","LF08","",0),
("Ranjna Jain","We",4,4,"M.TECH CSE 3","Paedagogical Skills Lab","LF04","",0),
("Ranjna Jain","We",7,7,"CSE 5D","Advanced Java (L)","KS10","",0),
("Ranjna Jain","Th",2,2,"B.Tech GenAI 1","Data Modelling & Visualization (L)","KS03","",0),
("Ranjna Jain","Th",7,7,"CSE 5D","Advanced Java (L)","KS09","",0),
("Ranjna Jain","Fr",7,7,"CSE 5D","Advanced Java (L)","LT09","",0),

("Ravi Chaturvedi","Mo",1,1,"CSE 5B/5C/5D","Deep Learning Essentials (L)","HS08","",0),
("Ravi Chaturvedi","Mo",6,7,"AIML 5A","Computer Architecture & Organisation Lab","LAB08","Group 1",0),
("Ravi Chaturvedi","Mo",8,9,"CSE 5A/5B","Deep Learning Essentials Lab","LAB02","G4",0),
("Ravi Chaturvedi","Tu",1,1,"AIML 5A","Computer Architecture & Organisation Lab","LAB04","Group 2",1),
("Ravi Chaturvedi","Tu",6,6,"CSE 5B/5C/5D","Deep Learning Essentials (L)","HT09","",1),
("Ravi Chaturvedi","Tu",7,8,"CSE 3A/3B/3C/M.E-3-S.M.A&E.V","Information Theory & Cryptography (L)","LT10","",1),
("Ravi Chaturvedi","We",3,4,"AIML 5A","Computer Architecture & Organisation (L)","LF03","",0),
("Ravi Chaturvedi","We",8,8,"AIML 3A","CST_Mentor-Mentee","LS04","",0),
("Ravi Chaturvedi","Th",1,1,"AIML 5A","Computer Architecture & Organisation (L)","LF09","",0),
("Ravi Chaturvedi","Fr",3,4,"AIML 5A","Computer Architecture & Organisation (L)","KS02","",0),
("Ravi Chaturvedi","Fr",7,7,"CSE 5B/5C/5D","Deep Learning Essentials (L)","HS08","",1),
("Ravi Chaturvedi","Fr",8,8,"CSE 3A/3B/3C/M.E-3-S.M.A&E.V","Information Theory & Cryptography (L)","LT03","",1),

("Sachin Lakra","Mo",7,7,"BCA CC 1/BCA FinTech 1","C Programming (L)","LF04","",0),
("Sachin Lakra","Tu",2,2,"B.Sc Forensic Orientation","UHV-I","","",0),
("Sachin Lakra","Tu",3,4,"BCA CC 1/BCA FinTech 1","C Programming Lab","LAB02","",0),
("Sachin Lakra","We",2,2,"B.Sc Forensic Orientation","UHV-I","","",0),
("Sachin Lakra","We",4,4,"CSE 7A/CSE 7B","Green Computing (L)","HS08","",0),
("Sachin Lakra","We",6,7,"BCA CC 1/BCA FinTech 1","C Programming Lab","LAB01","",0),
("Sachin Lakra","Th",2,2,"B.Sc Forensic Orientation","UHV-I","","",0),
("Sachin Lakra","Th",4,4,"CSE 7C","CST_Mentor-Mentee","HS08","",0),
("Sachin Lakra","Fr",2,2,"B.Sc Forensic Orientation","UHV-I","","",0),
("Sachin Lakra","Fr",3,3,"BCA CC 1/BCA FinTech 1","C Programming (L)","LS08","",0),
("Sachin Lakra","Fr",6,6,"CSE 7A/CSE 7B","Green Computing Lab","HT08","G1",0),
("Sachin Lakra","Fr",8,8,"CSE 3B","Introduction to Research","LT08","",0),

("Sanjay Singh","Mo",1,1,"CSE 5A/5B/5C/5D/AIML 5A/AIML 5B/FSD 5/CSTI 5","Animation and Rendering (L)","KS09","",0),
("Sanjay Singh","Mo",2,2,"CSE 5D","Computer Architecture & Organisation (L)","KS10","",0),
("Sanjay Singh","Mo",3,3,"CSE 5D","Computer Architecture & Organisation Lab","LAB09","Group 1",0),
("Sanjay Singh","Mo",8,9,"CSE 5A/5B/5C/5D/AIML 5A/AIML 5B/FSD 5/CSTI 5","Animation and Rendering Lab","LAB01","G9",0),
("Sanjay Singh","Tu",3,3,"CSE 5D","Computer Architecture & Organisation Lab","LAB08","Group 2",0),
("Sanjay Singh","Tu",6,6,"CSE 5A/5B/5C/5D/AIML 5A/AIML 5B/FSD 5/CSTI 5","Animation and Rendering (L)","HT03","",0),
("Sanjay Singh","Tu",7,7,"CSE 5D","Computer Architecture & Organisation (L)","KS10","",0),
("Sanjay Singh","We",1,1,"CSE 5D","CST_Mentor-Mentee","LS04","",0),
("Sanjay Singh","We",8,8,"CSE 7B/CSE 7C/AIML 7A/AIML 7B/AIML 7C","Image Editing & Animation Workshop","LAB08","Group 7",0),
("Sanjay Singh","Fr",6,6,"CSE 5D","Computer Architecture & Organisation (L)","KS10","",0),
("Sanjay Singh","Fr",8,8,"CSE 5A/5B/5C/5D/AIML 5A/AIML 5B/FSD 5/CSTI 5","Animation and Rendering (L)","KS02","",0),

("Shalu","Mo",3,3,"BCA CC3","Cloud Infrastructure and Services (L)","LT08","",0),
("Shalu","Mo",4,4,"CSTI 1/B.Tech GenAI 1/B.TECH QUANTUM 1","PS Using C (L)","LF03","",0),
("Shalu","Tu",1,2,"BCA CC3","Cloud Infrastructure and Services Lab","LAB03","",0),
("Shalu","We",2,2,"BCA CC3/BCA FinTech3","Introduction to Research","LT08","",0),
("Shalu","We",8,8,"CSTI 1/B.Tech GenAI 1/B.TECH QUANTUM 1","PS Using C Lab","LAB06","",0),
("Shalu","Th",6,7,"CSTI 1/B.Tech GenAI 1/B.TECH QUANTUM 1","PS Using C Lab","LAB09","",0),
("Shalu","Fr",2,2,"CSTI 1/B.Tech GenAI 1/B.TECH QUANTUM 1","PS Using C (L)","KS10","",0),
("Shalu","Fr",3,3,"BCA CC3","Cloud Infrastructure and Services (L)","LS08","",0),

("Sujata","Mo",3,3,"CSE 3A","Database Management System (L)","KS02","",0),
("Sujata","Mo",6,7,"CSE 3A","Database Management System Lab","LAB01","Group 1",0),
("Sujata","Tu",3,3,"CSE 5D","Operating Systems Lab","LAB03","Group 1",0),
("Sujata","Tu",9,9,"AIML 3C/FSD 3","Introduction to Research","LF04","",0),
("Sujata","We",2,2,"CSE 5D","Operating Systems (L)","KS09","",0),
("Sujata","We",3,3,"CSE 3A","Database Management System (L)","LT03","",0),
("Sujata","We",7,7,"AIML 7C","CST_Mentor-Mentee","LF04","",0),
("Sujata","We",8,8,"CSE 3A","Database Management System Lab","LAB07","Group 2",0),
("Sujata","Th",3,3,"CSE 5D","Operating Systems (L)","HS02","",0),
("Sujata","Th",6,6,"CSE 5D","Operating Systems (L)","LT03","",0),
("Sujata","Th",7,7,"CSE 3A","Database Management System (L)","LT09","",0),
("Sujata","Fr",1,1,"CSE 5D","Operating Systems Lab","LT03","Group 2",0),
]

with open('/home/claude/faculty-adjustment-finder/data/timetable_data.csv','a',newline='',encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerows(rows)

print(len(rows), "rows appended")
